blog/config/routes.rb
Rails.application.routes.draw do
    get 'articles/index'
    root  'articles#index'

    resources :articles do
    	resources :comments
    	end
    	
	resources :tags

end

blog/app/models/article.rb
class Article < ActiveRecord::Base
	has_many :taggings
	has_many :tags, through: :taggings
    has_many :comments, dependent: :destroy
    has_attached_file :image
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
    validates :title, presence: true,
    length: { minimum: 5 }
    
	def tag_list
 		 self.tags.collect do |tag|
 		   tag.name
 		 end.join(", ")
	end
	
	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
		new_or_found_tags = tag_names.collect{ |name| Tag.find_or_create_by(name: name) }
		self.tags= new_or_found_tags
	end
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

blog/app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :articles, through: :taggings
end

blog/app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	http_basic_authenticate_with name: "dhh", password: "secret", expect: [:index, :show]
	
    def index
        @articles = Article.all
    end
    
    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end
    
    def edit
        @article = Article.find(params[:id])
    end
    
    def create
        @article = Article.new(article_params)
       if @article.save
       flash.notice = "Artice has been Saved"
            redirect_to @article
       else
            render 'new'
       end
    end
    
    def update
        @article = Article.find(params[:id])
        
        if @article.update(article_params)
            redirect_to @article
        else
            render 'edit'
       end
    end
    
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end
    
    def article_params
        params.require(:article).permit(:title, :text, :tag_list, :image)
    end
    
    
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", only: [:destroy]
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
	end
	
 	def destroy
  		 @article = Article.find(params[:article_id])
   		 @comment = @article.comments.find(params[:id])
   		 @comment.destroy
	    redirect_to article_path(@article)
	end
	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

blog/app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def index
        @tags = Tag.all
    end

	def show
		@tag = Tag.find(params[:id])
	end
	
	def destroy
        @tag = Tag.find(params[:id])
        @tag.destroy
        redirect_to tags_path
    end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
#   def article_params
#     params.require(:article).permit(:title, :body, :tag_list)
#   end
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/tags_helper.rb
module TagsHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  
 <p>
  <%= f.label :tag_list %><br />
  <%= f.text_field :tag_list %>
 </p>
 
  <p>
  	<% if @article.image.exists? %>
  		<%= image_tag @article.image.url %><br>
  	<% end %>
  <%= f.label :image, "Attach an Image" %><br />
  <%= f.file_field :image %>
 </p>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

blog/app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

blog/app/views/articles/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>
<%= link_to "New Article", new_article_path, class: "new_article" %>


<h1>Listing articles</h1>

<table>
    <tr>
        <th>Title</th>
        <th>Text</th>
    <tr/>
    
    <% @articles.each do |article| %>
        <tr>
            <td><%= article.title %></td>
            <td><%= article.text %></td>
            <td><%= link_to 'Show', article_path(article) %></td>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
            <td><%= link_to 'Destroy', article_path(article),
            method: :delete,
            data: { confirm: "Are You Sure" } %></td>
        </tr>
     <% end %>
</table>

blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

blog/app/views/articles/show.html.erb
<h1>
    <strong>Title:</strong>
    <%= @article.title %>
</h1>

<p>
	Tags:
	<% @article.tags.each do |tag| %>
		<%= link_to tag.name, tag_path(tag) %>
	<% end %>
</p>


<p>
	<% if @article.image.exists? %>
		<%= image_tag @article.image.url %>
	<% end %>
</p>
<p>
    <strong>Text:</strong>
    <%= @article.text %>
</p>

<h3>Comments: <%= @article.comments.size %></h3>

<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

blog/app/views/comments/_comment.html.erb
    <p>
        <strong>Commmenter:</strong>
        <%= comment.commenter %>
    </p>
    
    <p>
        <strong>Comment:</strong>
        <%= comment.body %>
    </p>
    
    <p>
        <%= link_to 'Destroy Comment', [comment.article, comment],
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
    </p>

blog/app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p><%= flash.notice %></p>
<%= yield %>

</body>
</html>

blog/app/views/tags/index.html.erb
<h1>All Tags</h1>

<table>
	<% @tags.each do |tag| %>
		<tr>
			<td><%= link_to tag.name, tag_path(tag) %></td>
            <td><%= link_to 'Destroy', tag_path(tag),
            method: :delete,
            data: { confirm: "Are You Sure" } %></td>
		</tr>
	<% end %>
</table>

blog/app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>

blog/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>